import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { CSS2DRenderer, CSS2DObject } from 'three/addons/renderers/CSS2DRenderer.js';

// Configuration
const COLORS = {
    backbone: 0xff0000, // Red
    rungsYellow: 0xffcc00,
    rungsGreen: 0x66cc33,
    helicase: 0x0000ff, // Blue wedge
    polymerase: 0xffa500, // Orange
    primase: 0x008080, // Teal
    ligase: 0x00008b, // Dark Blue
    topoisomerase: 0x008000, // Green ring
    ssb: 0x800080, // Purple
    rnaPrimer: 0xff0000 // Red tint
};

const INFO_DATA = {
    'Helicase': 'Unzips the DNA double helix by breaking hydrogen bonds between base pairs.',
    'DNA Polymerase (Pol III)': 'Synthesizes new DNA strands by adding nucleotides to the 3\' end.',
    'Primase': 'Synthesizes RNA primers needed to start replication.',
    'Ligase': 'Joins Okazaki fragments together on the lagging strand.',
    'Topoisomerase': 'Relieves the strain generated by unwinding of DNA (supercoiling).',
    'SSB Proteins': 'Single-strand binding proteins stabilize the unwound DNA strands.',
    'Leading Strand': 'Replicated continuously in the 3\' to 5\' direction towards the fork.',
    'Lagging Strand': 'Replicated discontinuously in short sections (Okazaki fragments) away from the fork.',
    'Okazaki Fragment': 'Short sequences of DNA nucleotides synthesized discontinuously on the lagging strand.',
    'Parent DNA': 'The original double helix being replicated.',
    'RNA Primer': 'Short RNA sequence that provides a starting point for DNA synthesis.'
};

let scene, camera, renderer, labelRenderer, controls;
const raycaster = new THREE.Raycaster();
const mouse = new THREE.Vector2();
let interactables = [];
let selectedObject = null;

init();
animate();

function init() {
    const container = document.getElementById('canvas-container');

    // Scene
    scene = new THREE.Scene();
    scene.background = new THREE.Color(0xffffff); // White background

    // Camera
    camera = new THREE.PerspectiveCamera(45, container.clientWidth / container.clientHeight, 0.1, 1000);
    camera.position.set(0, 10, 60);

    // Renderer
    renderer = new THREE.WebGLRenderer({ antialias: true });
    renderer.setSize(container.clientWidth, container.clientHeight);
    container.appendChild(renderer.domElement);

    // Expose for debugging/testing
    window.scene = scene;
    window.camera = camera;
    window.renderer = renderer;

    // Label Renderer
    labelRenderer = new CSS2DRenderer();
    labelRenderer.setSize(container.clientWidth, container.clientHeight);
    labelRenderer.domElement.style.position = 'absolute';
    labelRenderer.domElement.style.top = '0px';
    labelRenderer.domElement.style.pointerEvents = 'none'; // Click-through
    container.appendChild(labelRenderer.domElement);

    // Lights
    const ambientLight = new THREE.AmbientLight(0xffffff, 0.8);
    scene.add(ambientLight);
    const dirLight = new THREE.DirectionalLight(0xffffff, 0.8);
    dirLight.position.set(10, 20, 20);
    scene.add(dirLight);

    // Controls
    controls = new OrbitControls(camera, renderer.domElement);
    controls.enableDamping = true;
    controls.target.set(0, 0, 0);

    // Tune Raycaster
    raycaster.params.Line.threshold = 1;
    raycaster.params.Mesh.threshold = 1;

    buildDNAModel();

    window.addEventListener('resize', onWindowResize);
    // Listen on the renderer element
    renderer.domElement.addEventListener('click', onMouseClick);
    renderer.domElement.addEventListener('pointermove', onPointerMove);
}

function buildDNAModel() {
    // Parent Hélix (Right side)
    const parentCurve1 = [];
    const parentCurve2 = [];
    const startX = 5;
    const endX = 35;
    const radius = 3;
    const twists = 3;

    for (let i = 0; i <= 50; i++) {
        const t = i / 50;
        const x = startX + t * (endX - startX);
        const angle = t * Math.PI * 2 * twists;
        parentCurve1.push(new THREE.Vector3(x, Math.cos(angle) * radius, Math.sin(angle) * radius));
        parentCurve2.push(new THREE.Vector3(x, Math.cos(angle + Math.PI) * radius, Math.sin(angle + Math.PI) * radius));
    }

    createTubeFromPoints(parentCurve1, COLORS.backbone, 'Parent DNA');
    createTubeFromPoints(parentCurve2, COLORS.backbone, 'Parent DNA');
    createRungsBetweenCurves(parentCurve1, parentCurve2, 15, 'Parent DNA');

    // Fork (x=0 to x=5) and Templates
    const forkX = 5;

    // Top Template (Lagging)
    const topCurvePath = new THREE.CatmullRomCurve3([
        new THREE.Vector3(-35, 8, 0),
        new THREE.Vector3(-15, 8, 0),
        new THREE.Vector3(0, 6, 0),
        new THREE.Vector3(5, Math.cos(0) * radius, Math.sin(0) * radius)
    ]);

    // Bottom Template (Leading)
    const bottomCurvePath = new THREE.CatmullRomCurve3([
        new THREE.Vector3(-35, -8, 0),
        new THREE.Vector3(-15, -8, 0),
        new THREE.Vector3(0, -6, 0),
        new THREE.Vector3(5, Math.cos(Math.PI) * radius, Math.sin(Math.PI) * radius)
    ]);

    createTubeFromCurve(topCurvePath, COLORS.backbone, 'Lagging Strand');
    createTubeFromCurve(bottomCurvePath, COLORS.backbone, 'Leading Strand');

    // Leading Synthesis (Bottom)
    const leadingNewPoints = bottomCurvePath.getPoints(50).filter(p => p.x < -5 && p.x > -40);
    const leadingNewOffset = leadingNewPoints.map(p => new THREE.Vector3(p.x, p.y + 2, p.z));
    createTubeFromPoints(leadingNewOffset, COLORS.backbone, 'Leading Strand');
    createRungsDirect(bottomCurvePath.getPoints(60).filter(p => p.x < -5 && p.x > -35), leadingNewOffset, 'Leading Strand');

    // Polymerase (Leading)
    const leadPol = createBox(new THREE.Vector3(-3, -7, 0), COLORS.polymerase, 'DNA Polymerase (Pol III)');
    leadPol.rotation.z = -0.2;

    // Lagging Synthesis (Top - Okazaki)
    function createFragment(startX, endX) {
        const curvePoints = topCurvePath.getPoints(100);
        const segment = curvePoints.filter(p => p.x >= startX && p.x <= endX);
        if (segment.length < 2) return;
        const offsetSegment = segment.map(p => new THREE.Vector3(p.x, p.y - 2, p.z));
        createTubeFromPoints(offsetSegment, COLORS.backbone, 'Okazaki Fragment');
        createRungsDirect(segment, offsetSegment, 'Okazaki Fragment');
    }
    createFragment(-30, -20);
    createFragment(-15, -8);
    createFragment(-5, -2);

    // Ligase
    const ligase = createCylinder(new THREE.Vector3(-18, 6, 0), COLORS.ligase, 'Ligase');
    ligase.rotation.z = Math.PI / 2;

    // Polymerase (Lagging)
    createBox(new THREE.Vector3(-2, 5, 0), COLORS.polymerase, 'DNA Polymerase (Pol III)');

    // Primase
    const primase = createCylinder(new THREE.Vector3(2, 6, 0), COLORS.primase, 'Primase');
    primase.scale.set(1.5, 1, 1.5);
    primase.rotation.x = Math.PI / 2;

    // Helicase
    const helicaseGeo = new THREE.ConeGeometry(4, 8, 32);
    const helicaseMat = new THREE.MeshLambertMaterial({ color: COLORS.helicase });
    const helicase = new THREE.Mesh(helicaseGeo, helicaseMat);
    helicase.position.set(5, 0, 0);
    helicase.rotation.z = -Math.PI / 2;
    helicase.name = 'Helicase';
    scene.add(helicase);
    interactables.push(helicase);
    addLabel(helicase, 'Helicase');

    // Topoisomerase
    const topoGeo = new THREE.TorusGeometry(5, 1.5, 16, 100);
    const topoMat = new THREE.MeshLambertMaterial({ color: COLORS.topoisomerase });
    const topo = new THREE.Mesh(topoGeo, topoMat);
    topo.position.set(20, 0, 0);
    topo.rotation.y = Math.PI / 2;
    topo.name = 'Topoisomerase';
    scene.add(topo);
    interactables.push(topo);
    addLabel(topo, 'Topoisomerase');

    // SSBs
    [new THREE.Vector3(0, 7, 0), new THREE.Vector3(-0.5, -7, 0), new THREE.Vector3(2, 6.5, 0)].forEach(p => {
        const ssb = new THREE.Mesh(new THREE.SphereGeometry(0.8), new THREE.MeshLambertMaterial({ color: COLORS.ssb }));
        ssb.position.copy(p);
        ssb.name = 'SSB Proteins';
        scene.add(ssb);
        interactables.push(ssb);
    });

    // Text Labels
    addLabel({ position: new THREE.Vector3(-35, 9, 0) }, "3'");
    addLabel({ position: new THREE.Vector3(-35, 7, 0) }, "5'");
    addLabel({ position: new THREE.Vector3(-35, -7, 0) }, "5'");
    addLabel({ position: new THREE.Vector3(-35, -9, 0) }, "3'");
    addLabel({ position: new THREE.Vector3(-40, 8, 0) }, "Lagging\nstrand");
    addLabel({ position: new THREE.Vector3(-40, -8, 0) }, "Leading\nstrand");
}

function createTubeFromCurve(curve, color, name) {
    const geo = new THREE.TubeGeometry(curve, 64, 0.6, 8, false);
    const mat = new THREE.MeshLambertMaterial({ color: color });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.name = name;
    scene.add(mesh);
    interactables.push(mesh);
    return mesh;
}

function createTubeFromPoints(points, color, name) {
    if (points.length < 2) return;
    const curve = new THREE.CatmullRomCurve3(points);
    return createTubeFromCurve(curve, color, name);
}

function createRungsBetweenCurves(curvePoints1, curvePoints2, count, name) {
    const step = Math.floor(curvePoints1.length / count);
    for (let i = 0; i < curvePoints1.length; i += step) {
        if (!curvePoints2[i]) break;
        createRung(curvePoints1[i], curvePoints2[i], name);
    }
}

function createRungsDirect(points1, points2, name) {
    const len = Math.min(points1.length, points2.length);
    for (let i = 0; i < len; i += 4) {
        createRung(points1[i], points2[i], name);
    }
}

function createRung(p1, p2, name) {
    const dist = p1.distanceTo(p2);
    const geo = new THREE.CylinderGeometry(0.3, 0.3, dist / 2, 8);
    const mat1 = new THREE.MeshLambertMaterial({ color: COLORS.rungsYellow });
    const mat2 = new THREE.MeshLambertMaterial({ color: COLORS.rungsGreen });

    const half1 = new THREE.Mesh(geo, mat1);
    const half2 = new THREE.Mesh(geo, mat2);

    half1.position.copy(p1).lerp(p2, 0.25);
    half2.position.copy(p1).lerp(p2, 0.75);
    half1.lookAt(p2);
    half2.lookAt(p2);
    half1.rotateX(Math.PI / 2);
    half2.rotateX(Math.PI / 2);

    half1.name = name;
    half2.name = name;
    scene.add(half1, half2);
    interactables.push(half1, half2);
}

function createBox(pos, color, name) {
    const geo = new THREE.BoxGeometry(4, 4, 4);
    const mat = new THREE.MeshLambertMaterial({ color: color });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.position.copy(pos);
    mesh.name = name;
    scene.add(mesh);
    interactables.push(mesh);
    addLabel(mesh, name);
    return mesh;
}

function createCylinder(pos, color, name) {
    const geo = new THREE.CylinderGeometry(1.5, 1.5, 4, 32);
    const mat = new THREE.MeshLambertMaterial({ color: color });
    const mesh = new THREE.Mesh(geo, mat);
    mesh.position.copy(pos);
    mesh.name = name;
    scene.add(mesh);
    interactables.push(mesh);
    addLabel(mesh, name);
    return mesh;
}

function addLabel(object, text) {
    const div = document.createElement('div');
    div.className = 'model-label';
    div.innerText = text;
    const label = new CSS2DObject(div);
    if (object.position) {
        label.position.copy(object.position);
        label.position.y += 3;
    }
    if (object instanceof THREE.Object3D) object.add(label);
    else scene.add(label);
}

// Interaction
function onPointerMove(event) {
    const rect = renderer.domElement.getBoundingClientRect();
    mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
    mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

    raycaster.setFromCamera(mouse, camera);
    const intersects = raycaster.intersectObjects(interactables);

    if (intersects.length > 0) {
        document.body.style.cursor = 'pointer';
    } else {
        document.body.style.cursor = 'default';
    }
}

function onMouseClick(event) {
    // Rely on updated mouse pos from pointermove, or re-calc just in case
    const rect = renderer.domElement.getBoundingClientRect();
    mouse.x = ((event.clientX - rect.left) / rect.width) * 2 - 1;
    mouse.y = -((event.clientY - rect.top) / rect.height) * 2 + 1;

    raycaster.setFromCamera(mouse, camera);
    const intersects = raycaster.intersectObjects(interactables);

    if (intersects.length > 0) {
        const object = intersects[0].object;
        const name = object.name;

        if (name && INFO_DATA[name]) {
            showInfo(name, INFO_DATA[name]);

            // Highlight
            if (selectedObject && selectedObject !== object) restoreObjectStyle(selectedObject);
            selectedObject = object;
            highlighObject(selectedObject);
        }
    } else {
        // Clicked background
        if (selectedObject) {
            restoreObjectStyle(selectedObject);
            selectedObject = null;
        }
        hideInfo();
    }
}

function highlighObject(obj) {
    obj.currentScale = obj.scale.clone();
    obj.scale.multiplyScalar(1.2);
    if (obj.material && obj.material.emissive) {
        obj.currentEmissive = obj.material.emissive.getHex();
        obj.material.emissive.setHex(0x555555);
    }
}

function restoreObjectStyle(obj) {
    if (obj.currentScale) obj.scale.copy(obj.currentScale);
    else obj.scale.setScalar(1);

    if (obj.material && obj.material.emissive) {
        obj.material.emissive.setHex(obj.currentEmissive || 0x000000);
    }
}

function showInfo(title, desc) {
    const infoPanel = document.getElementById('info-panel');
    document.getElementById('info-title').innerText = title;
    document.getElementById('info-desc').innerText = desc;
    infoPanel.classList.add('visible');
}

function hideInfo() {
    document.getElementById('info-panel').classList.remove('visible');
}

function onWindowResize() {
    const container = document.getElementById('canvas-container');
    camera.aspect = container.clientWidth / container.clientHeight;
    camera.updateProjectionMatrix();
    renderer.setSize(container.clientWidth, container.clientHeight);
    labelRenderer.setSize(container.clientWidth, container.clientHeight);
}

function animate() {
    requestAnimationFrame(animate);
    controls.update();
    renderer.render(scene, camera);
    labelRenderer.render(scene, camera);
}
